# Generated by Django 2.2.3 on 2019-11-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPackge',
            fields=[
                ('id', models.AutoField(help_text='id', primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=50, verbose_name='phone_number')),
                ('send_time', models.DateField(verbose_name='send_time')),
                ('content', models.CharField(max_length=50, verbose_name='content')),
                ('sign_name', models.CharField(max_length=50, verbose_name='sign_name')),
                ('dest_code', models.CharField(max_length=50, verbose_name='dest_code')),
                ('sequence_id', models.IntegerField(verbose_name='sequence_id')),
            ],
        ),
    ]
