# Generated by Django 2.2.3 on 2019-11-28 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliyun_sms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderPackge',
            new_name='SmsUp',
        ),
    ]
