# Generated by Django 2.2.3 on 2019-11-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliyun_sms', '0002_auto_20191128_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsReport',
            fields=[
                ('id', models.AutoField(help_text='id', primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=50, verbose_name='phone_number')),
                ('send_time', models.DateField(verbose_name='send_time')),
                ('report_time', models.DateField(verbose_name='report_time')),
                ('success', models.BooleanField(verbose_name='success')),
                ('err_code', models.CharField(max_length=150, verbose_name='err_code')),
                ('err_msg', models.CharField(max_length=150, verbose_name='err_msg')),
                ('sms_size', models.CharField(max_length=150, verbose_name='sms_size')),
                ('biz_id', models.CharField(max_length=150, verbose_name='biz_id')),
                ('out_id', models.CharField(max_length=150, verbose_name='out_id')),
            ],
        ),
        migrations.AlterField(
            model_name='smsup',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='smsup',
            name='dest_code',
            field=models.CharField(max_length=150, verbose_name='dest_code'),
        ),
        migrations.AlterField(
            model_name='smsup',
            name='sign_name',
            field=models.CharField(max_length=150, verbose_name='sign_name'),
        ),
    ]
