# Generated by Django 2.2.3 on 2019-11-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliyun_sms', '0003_auto_20191128_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsreport',
            name='report_time',
            field=models.DateTimeField(verbose_name='report_time'),
        ),
        migrations.AlterField(
            model_name='smsreport',
            name='send_time',
            field=models.DateTimeField(verbose_name='send_time'),
        ),
        migrations.AlterField(
            model_name='smsup',
            name='send_time',
            field=models.DateTimeField(verbose_name='send_time'),
        ),
    ]
