# Generated by Django 2.2.3 on 2019-11-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliyun_sms', '0004_auto_20191128_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsSign',
            fields=[
                ('id', models.AutoField(help_text='id', primary_key=True, serialize=False)),
                ('sing_name', models.CharField(max_length=12, verbose_name='SignName')),
                ('sign_source', models.IntegerField(choices=[(0, '企事业单位的全称或简称'), (1, '工信部备案网站的全称或简称'), (2, 'APP应用的全称或简称'), (3, '公众号或小程序的全称或简称'), (4, '电商平台店铺名的全称或简称'), (5, '商标名的全称或简称')], verbose_name='SignSource')),
                ('remark', models.CharField(max_length=200, verbose_name='Remark')),
            ],
        ),
        migrations.AlterField(
            model_name='smsreport',
            name='biz_id',
            field=models.CharField(max_length=550, verbose_name='biz_id'),
        ),
        migrations.AlterField(
            model_name='smsreport',
            name='err_code',
            field=models.CharField(max_length=550, verbose_name='err_code'),
        ),
        migrations.AlterField(
            model_name='smsreport',
            name='err_msg',
            field=models.CharField(max_length=550, verbose_name='err_msg'),
        ),
        migrations.AlterField(
            model_name='smsreport',
            name='out_id',
            field=models.CharField(max_length=550, verbose_name='out_id'),
        ),
        migrations.AlterField(
            model_name='smsreport',
            name='sms_size',
            field=models.CharField(max_length=550, verbose_name='sms_size'),
        ),
    ]
