# Generated by Django 2.2.3 on 2019-12-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliyun_sms', '0005_auto_20191129_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.IntegerField(choices=[(0, '验证码'), (2, '短信通知'), (2, '推广短信'), (3, '国际/港澳台消息')], verbose_name='TemplateType')),
                ('template_name', models.CharField(max_length=30, verbose_name='TemplateName')),
                ('template_content', models.CharField(max_length=500, verbose_name='TemplateContent')),
                ('remark', models.CharField(max_length=100, verbose_name='Remark')),
            ],
        ),
    ]
